Difference issue
rugleb/JsonCompare pull request #37
Opened 2023-11-21 22:07 UTC by MiyamotoAkira

Solving issue #29. Use the first difference

2023-11-21 22:13 UTC, MiyamotoAkira commented
Though `test_simple_list_with_dicts` shows the fix for the specific issue, I think the other two new tests are more interesting. Both `test_list_with_dicts` and `test_list_with_dicts_with_duplicates` show really unexpected results.

I think a better general solution would be to cache entries that have been matched (including their index) so they could be ignored on following difference findings. 

Maybe the code added (`_min_diff`) is enough for now, as the other two tests will have the same issues with  `_max_diff`, just giving different values.

2023-11-21 22:15 UTC, MiyamotoAkira commented
Ah, I left the tests, to document the current behaviour. Maybe a comment could left on each test to indicate that the behaviour should be revisited

2023-11-24 20:57 UTC, rugleb commented
> Ah, I left the tests to document the current behaviour. Maybe a comment could be left on each test to indicate that the behaviour should be revisited

Yes, add it with link on u comment please.

2023-11-24 20:57 UTC, rugleb requested changes

2023-11-24 20:57 UTC, rugleb commented on tests/test_compare.py
> +        print(diff)
Remove it pls.
PS: below too.

2023-11-25 17:18 UTC, MiyamotoAkira commented on tests/test_compare.py
> +        print(diff)
ooooops

2023-11-25 17:25 UTC, MiyamotoAkira commented
Both things done

2023-12-05 18:23 UTC, merged